spring.data.mongodb.uri=${SHAPARAK_MONGODB_URI:mongodb://localhost:27017/shaparak}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

server.port=${SHAPARAK_PORT:8082}
bank.a.base-url=${BANK_A_BASE_URL:http://localhost:8080/bank}
bank.b.base-url=${BANK_B_BASE_URL:http://localhost:8081/bank}
