spring.application.name=developer-console
server.address=${CONSOLE_HOST:127.0.0.1}
server.port=${CONSOLE_PORT:8090}
spring.datasource.url=${CONSOLE_MYSQL_URL:jdbc:mysql://localhost:3306/bank_a}
spring.datasource.username=${CONSOLE_MYSQL_USERNAME:root}
spring.datasource.password=${CONSOLE_MYSQL_PASSWORD:root}
spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.initialization-fail-timeout=-1
spring.data.mongodb.uri=${CONSOLE_MONGODB_URI:mongodb://localhost:27017/psp?serverSelectionTimeoutMS=1500&connectTimeoutMS=1000}
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.connection-timeout=2000
console.psp-url=${CONSOLE_PSP_URL:http://localhost:8084}
console.bank-a-url=${CONSOLE_BANK_A_URL:http://localhost:8080/bank}
console.bank-b-url=${CONSOLE_BANK_B_URL:http://localhost:8081/bank}
console.shaparak-url=${CONSOLE_SHAPARAK_URL:http://localhost:8082}
