spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

spring.data.mongodb.uri=${PSP_MONGODB_URI:mongodb://localhost:27017/psp}

server.port=${PSP_PORT:8084}
