spring.application.name=bank-a
spring.datasource.url=${BANK_A_DB_URL:jdbc:mysql://localhost:3306/bank_a}
spring.datasource.username=${BANK_A_DB_USERNAME:root}
spring.datasource.password=${BANK_A_DB_PASSWORD:root}
server.port=${BANK_A_PORT:8080}
server.servlet.context-path=/bank
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.error.include-message=always
